#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED

#define ID_TIMER1 1

// START POSITION OF THE WINDOW (AFTER RESIZING):
#define START_POSITION_OX 0
#define START_POSITION_OY 0

// DEFAULT SIZE OF WINDOW:
#define DEFAULT_WINDOW_SIZE_OX 780
#define DEFAULT_WINDOW_SIZE_OY 570

// MIN SIZE OF THE WINDOW:
#define MIN_WINDOW_SIZE_OX 560
#define MIN_WINDOW_SIZE_OY 470

// MAX SIZE OF THE WINDOW:
#define MAX_WINDOW_SIZE_OX 1366
#define MAX_WINDOW_SIZE_OY 768

#endif // DEFINES_H_INCLUDED
