#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED

#define ID_BUTTON1 1
#define ID_BUTTON2 2


#define ID_FILE_OPEN 3
#define ID_FILE_SAVE 4
#define ID_FILE_SAVE_AS 5
#define ID_FILE_HEX_VIEW 6
#define ID_FILE_EXIT 7


#define ID_EDIT_RESIZE_BUTTON1_DEFAULT 8
#define ID_EDIT_RESIZE_BUTTON1_BIGGER 9
#define ID_EDIT_RESIZE_BUTTON1_SMALLER 10

#define ID_EDIT_RESIZE_BUTTON2_DEFAULT 11
#define ID_EDIT_RESIZE_BUTTON2_BIGGER 12
#define ID_EDIT_RESIZE_BUTTON2_SMALLER 13

#define ID_EDIT_RESIZE_WINDOW_450X300 14
#define ID_EDIT_RESIZE_WINDOW_550X420 15
#define ID_EDIT_RESIZE_WINDOW_700X512 16
#define ID_EDIT_RESIZE_WINDOW_800X600 17
#define ID_EDIT_RESIZE_WINDOW_1012X720 18

#define ID_EDIT_SEARCH 19


#define ID_HELP_ABOUT 20


#define MIN_WINDOW_SIZE_OX 450
#define MIN_WINDOW_SIZE_OY 300


#endif // DEFINES_H_INCLUDED
