#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED


//
#define number_of_persons 14
//
#define ID_VSCROLLBAR 1001
#define ID_HSCROLLBAR 1002

#define ID_BUTTON1 1
#define ID_BUTTON2 2
#define ID_BUTTON3 3


#define ID_FILE_OPEN_DATABASE 4
#define ID_FILE_SAVE 5
#define ID_FILE_SAVE_AS 6
#define ID_FILE_HEX_VIEW 7
#define ID_FILE_EXIT 8


#define ID_EDIT_RESIZE_BUTTON1_DEFAULT 9
#define ID_EDIT_RESIZE_BUTTON1_BIGGER 10
#define ID_EDIT_RESIZE_BUTTON1_SMALLER 11

#define ID_EDIT_RESIZE_BUTTON2_DEFAULT 12
#define ID_EDIT_RESIZE_BUTTON2_BIGGER 13
#define ID_EDIT_RESIZE_BUTTON2_SMALLER 14

#define ID_EDIT_RESIZE_WINDOW_780X430 15
#define ID_EDIT_RESIZE_WINDOW_820X460 16
#define ID_EDIT_RESIZE_WINDOW_900X512 17
#define ID_EDIT_RESIZE_WINDOW_950X620 18
#define ID_EDIT_RESIZE_WINDOW_1366X768 19

#define ID_EDIT_SEARCH 20


#define ID_HELP_ABOUT 21

#define MIN_WINDOW_SIZE_OX 780
#define MIN_WINDOW_SIZE_OY 430


#endif // DEFINES_H_INCLUDED
