#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED

// ELEMENTS:
#define ID_RECTANGLE 0
#define ID_SQUARE 1
#define ID_ELLIPSE 2
#define ID_CIRCLE 3
#define ID_STRAIGHT_LINE 4
#define ID_POLYLINE 5
#define ID_BEZIER_CURVE 6
// ***********************

// FILE:
#define ID_FILE_VIEW 1001
#define ID_FILE_EXIT 1002

// EDIT -> CREATE:
#define ID_EDIT_CREATE_RECTANGLE 1003
#define ID_EDIT_CREATE_SQUARE 1004
#define ID_EDIT_CREATE_ELLIPSE 1005
#define ID_EDIT_CREATE_CIRCLE 1006
#define ID_EDIT_CREATE_STRAIGHT_LINE 1007
#define ID_EDIT_CREATE_POLYLINE 1008
#define ID_EDIT_CREATE_BEZIER_CURVE 1009

// EDIT -> SET -> WINDOW SIZE:
#define ID_EDIT_SET_WINDOW_SIZE_DEFAULT 1010
#define ID_EDIT_SET_WINDOW_SIZE_MINIMUM 1011
#define ID_EDIT_SET_WINDOW_SIZE_MAXIMUM 1012

// EDIT -> SET -> COLOR:
#define ID_EDIT_SET_COLOR_RED 1013
#define ID_EDIT_SET_COLOR_GREEN 1014
#define ID_EDIT_SET_COLOR_BLUE 1015
#define ID_EDIT_SET_COLOR_WHITE 1016
#define ID_EDIT_SET_COLOR_BLACK 1017
#define ID_EDIT_SET_COLOR_PROPER_COLOR 1018

// EDIT -> SET -> ZOOM:
#define ID_EDIT_SET_ZOOM_IN 1019
#define ID_EDIT_SET_ZOOM_OUT 1020

// EDIT -> SET -> MOUSE:
#define ID_EDIT_SET_MOUSE_DEFAULT 1021
#define ID_EDIT_SET_MOUSE_ERASER 1022
#define ID_EDIT_SET_MOUSE_TASSEL 1023

// EDIT -> UNDO
#define ID_EDIT_UNDO 1024

// ABOUT:
#define ID_ABOUT_SETTING_WINDOW_SIZE 1025
#define ID_ABOUT_CHOOSING_COLOR 1026

// ABOUT -> FIGURES:
#define ID_ABOUT_FIGURES_RECTANGLE 1027
#define ID_ABOUT_FIGURES_SQUARE 1028
#define ID_ABOUT_FIGURES_ELLIPSE 1029
#define ID_ABOUT_FIGURES_CIRCLE 1030
#define ID_ABOUT_FIGURES_STRAIGHT_LINE 1031
#define ID_ABOUT_FIGURES_POLYLINE 1032
#define ID_ABOUT_FIGURES_BEZIER_CURVE 1033

// ABOUT:
#define ID_ABOUT_AUTHOR 1034

// START POSITION OF THE WINDOW (AFTER RESIZING):
#define START_POSITION_OX 0
#define START_POSITION_OY 0

// DEFAULT SIZE OF WINDOW:
#define DEFAULT_WINDOW_SIZE_OX 780
#define DEFAULT_WINDOW_SIZE_OY 570

// MIN SIZE OF THE WINDOW:
#define MIN_WINDOW_SIZE_OX 560
#define MIN_WINDOW_SIZE_OY 470

// MAX SIZE OF THE WINDOW:
#define MAX_WINDOW_SIZE_OX 1366
#define MAX_WINDOW_SIZE_OY 768

#endif // DEFINES_H_INCLUDED
